//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vindorel_Online.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Towns
    {
        public int TownId { get; set; }
        public int UserId { get; set; }
        public int x { get; set; }
        public int y { get; set; }
        public string TownName { get; set; }
        public int Wood { get; set; }
        public int Food { get; set; }
        public int Iron { get; set; }
        public int Population { get; set; }
        public int BuildingSpace1_Type { get; set; }
        public int BuildingSpace1_Level { get; set; }
        public int BuildingSpace2_Type { get; set; }
        public int BuildingSpace2_Level { get; set; }
        public int BuildingSpace3_Type { get; set; }
        public int BuildingSpace3_Level { get; set; }
        public int BuildingSpace4_Type { get; set; }
        public int BuildingSpace4_Level { get; set; }
        public int BuildingSpace5_Type { get; set; }
        public int BuildingSpace5_Level { get; set; }
        public int BuildingSpace6_Type { get; set; }
        public int BuildingSpace6_Level { get; set; }
        public int BuildingSpace7_Type { get; set; }
        public int BuildingSpace7_Level { get; set; }
        public int BuildingSpace8_Type { get; set; }
        public int BuildingSpace8_Level { get; set; }
        public int BuildingSpace9_Type { get; set; }
        public int BuildingSpace9_Level { get; set; }
        public int BuildingSpace10_Type { get; set; }
        public int BuildingSpace10_Level { get; set; }
        public int BuildingSpace11_Type { get; set; }
        public int BuildingSpace11_Level { get; set; }
    
        public virtual Players Players { get; set; }
    }
}
